# Generated by Django 3.1.4 on 2020-12-15 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ptchart', '0001_initial'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchquestionresponse',
            name='research_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchquestion'),
        ),
        migrations.AddField(
            model_name='researchquestionresponse',
            name='research_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchstudy'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptchart.patient'),
        ),
    ]
