# Generated by Django 3.1.4 on 2020-12-15 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ptchart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('patient', models.ManyToManyField(to='ptchart.Patient')),
            ],
            options={
                'verbose_name_plural': 'Research Studies',
            },
        ),
        migrations.CreateModel(
            name='ResearchQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.TextField()),
                ('text', models.TextField()),
                ('research_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researchstudy')),
            ],
            options={
                'verbose_name_plural': 'Research Questions',
            },
        ),
    ]
